---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-prometheus
  labels:
    app: spring-prometheus
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-prometheus
  template:
    metadata:
      labels:
        app: spring-prometheus
        version: 1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      serviceAccountName: spring-prometheus
      containers:
        - name: spring-prometheus
          image: boeboe/spring-prometheus:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-spring
              containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "500m"
