---
apiVersion: v1
kind: Service
metadata:
  name: spring-prometheus
  labels:
    app: spring-prometheus
    version: 1.0.0
spec:
  type: NodePort
  ports:
    - name: http-spring
      port: 8080
      targetPort: http-spring
  selector:
    app: spring-prometheus
